"""new fields in user model

Revision ID: 734431dc1d37
Revises: 2665163df984
Create Date: 2024-03-06 21:08:52.289797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734431dc1d37'
down_revision = '2665163df984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
